local utils = require 'utils'

local keymaps = {
  { 'i', 'jk', '<Esc>', utils.default_keymap_opt },
  { 'n', '<leader>e', '<cmd>Neotree toggle<cr>', { desc = '显示/隐藏NeoTree' } },
  { 'n', '<leader>q', '<cmd>Telescope file_browser<cr>', { desc = '显示/隐藏Filer Browser' } },
  -- 几乎用不到
  -- { 'n', '<leader>ef', '<cmd>Neotree focus<cr>',  { desc = '切换到NeoTree' } },
  -- { "n", "<leader>ec", "<cmd>Neotree close<cr>", utils.default_keymap_opt },
  { 'i', '<M-j>', '<Down>', utils.default_keymap_opt },
  { 'n', '<M-j>', 'ddp', utils.default_keymap_opt },
  { 'i', '<M-k>', '<Up>', utils.default_keymap_opt },
  { 'n', '<M-k>', 'dd2kp', utils.default_keymap_opt },
  { 'i', '<M-h>', '<Left>', utils.default_keymap_opt },
  { 'i', '<M-l>', '<Right>', utils.default_keymap_opt },
  { 'n', '<M-d>', 'yyp', utils.default_keymap_opt },
  { 'n', '<M-o>', 'o<Esc>', utils.default_keymap_opt },
  { 'i', '<M-p>', '<C-r>+', utils.default_keymap_opt },
  { 'i', '<M-0>', '<c-r>"', utils.default_keymap_opt },
  { { 'n', 'v' }, '<M-p>', '"+p', utils.default_keymap_opt },
  { { 'n', 'v' }, '<M-0>', '""p', utils.default_keymap_opt },
  { { 'v', 'o', 'n' }, 'H', '^', utils.default_keymap_opt },
  { { 'v', 'o', 'n' }, 'L', '$', utils.default_keymap_opt },
  { 'n', '<M-v>', '<C-v>', utils.default_keymap_opt },
  { 'n', '<M-b>', '<C-o>', utils.default_keymap_opt },
  { 'n', '<M-\\>', '<cmd>split<cr>', utils.default_keymap_opt },
  { 'n', '\\', '<cmd>vsplit<cr>', utils.default_keymap_opt },
  -- { "n", "<M-]>", "<C-f>", utils.default_keymap_opt },
  -- { "n", "<M-[>", "<C-u>", utils.default_keymap_opt },
  { 'n', 'ss', '<cmd>HopChar1<cr>', { desc = '单个字符搜索' } },
  { 'n', 'sc', '<cmd>HopChar2<cr>', { desc = '两个字符搜索' } },
  { 'n', 'sw', '<cmd>HopWord<cr>', { desc = '单词搜索' } },
  { 'n', 'sp', '<cmd>HopPattern<cr>', { desc = '正则搜索' } },
  { 'n', 'sh', '<C-w>h', { desc = '切换到左侧窗口' } },
  { 'n', 'sl', '<C-w>l', { desc = '切换到右侧窗口' } },
  { 'n', 'sj', '<C-w>j', { desc = '切换到下方窗口' } },
  { 'n', 'sk', '<C-w>k', { desc = '切换到上方窗口' } },
  { 'n', '<M-=>', '<C-w>10>', { desc = '窗口宽度扩大' } },
  { 'n', '<M-->', '<C-w>10<', { desc = '窗口宽度缩小' } },
  { 'v', '<', '<gv', { desc = '避免visual模式下处理缩进之后，选区丢失' } },
  { 'v', '>', '>gv', { desc = '避免visual模式下处理缩进之后，选区丢失' } },
  { 'v', 'p', '"_dP', { desc = '避免visual模式下粘贴影响正常yank的register' } },
  { 'n', ']]', '<cmd>BufferLineCycleNext<cr>', { desc = '切换下一个Tab签' } },
  { 'n', '[[', '<cmd>BufferLineCyclePrev<cr>', { desc = '切换上一个Tab签' } },
  { 'n', '=', '<cmd>BufferLinePick<cr>', { desc = '选择跳转指定Tab签' } },
  { 'n', '-', '<cmd>BufferLinePickClose<cr>', { desc = '选择关闭指定Tab签' } },
  { 'n', '<leader>g', '<cmd>GitBlameToggle<cr>', { desc = '显示/隐藏Git Blame' } },
  { 'n', '<leader>ww', '<cmd>lua require("spectre").toggle()<CR>', { desc = '显示/隐藏Spectre' } },
  {
    'n',
    '<leader>ws',
    '<cmd>lua require("spectre").open_visual({select_word=true})<CR>',
    { desc = '搜索当前单词(spectre)' },
  },
  {
    'n',
    '<leader>wS',
    '<cmd>lua require("spectre").open_visual()<CR>',
    { desc = '搜索当前单词(spectre)' },
  },
  {
    'n',
    '<leader>wb',
    '<cmd>lua require("spectre").open_file_search({select_word=true})<CR>',
    { desc = '只在当前Buffer搜索' },
  },
  { 'n', '<leader>mm', '<Plug>(Marks-toggle)', { noremap = false, desc = '添加/删除标签' } },
  { 'n', '<leader>ma', '<Plug>(Marks-set)', { noremap = false, desc = '设置标签，需指定标签名' } },
  { 'n', '<leader>mp', '<Plug>(Marks-preview)', { noremap = false, desc = '预览标签位置文本' } },
  { 'n', '<leader>mx', '<Plug>(Marks-deleteline)', { noremap = false, desc = '删除本行标签' } },
  { 'n', '<leader>md', '<Plug>(Marks-deletebuf)', { noremap = false, desc = '删除文件标签' } },
  { 'n', '<leader>mb', '<cmd>MarksListBuf<CR>', { desc = '列出当前文件所有标签' } },
  { 'n', '<leader>ml', '<cmd>MarksListAll<CR>', { desc = '列出所有文件所有标签' } },
  { 'v', '<C-r>', '"hy:%s/<C-r>h//gc<left><left><left>', { desc = '替换当前选择的文本(逐个确认)' } },
  { 'n', '<leader>df', '<cmd>DiffviewFileHistory %<CR>', { desc = '打开Diffview(文件历史)' } },
  { 'n', '<leader>do', '<cmd>DiffviewOpen <CR>', { desc = '打开Diffview(默认模式)' } },
  { 'n', '<leader>dc', '<cmd>DiffviewClose <CR>', { desc = '退出Diffview' } },
  { 'n', '<leader>k', '<Plug>(git-messenger)', { desc = '显示当前光标下的git信息' } },
}

utils.set_keymap(keymaps)
