local M = {
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  git = {
    added = ' ',
    modified = ' ',
    removed = ' ',
    topdelete = '󰚃',
    changedelete = '󰮈',
    untracked = '',
    branch = '',
    renamed = '',
    ignored = '',
    unstaged = '󰄷',
    staged = '󰄸',
    conflict = '',
  },
  kinds = {
    Array = '󰅨',
    Boolean = ' ',
    Class = ' ',
    Color = ' ',
    Constant = ' ',
    Constructor = ' ',
    Copilot = ' ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = '󰈮 ',
    Folder = ' ',
    Function = ' ',
    Interface = ' ',
    Key = ' ',
    Keyword = ' ',
    Method = ' ',
    Module = ' ',
    Namespace = ' ',
    Null = ' ',
    Number = ' ',
    Object = ' ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    String = ' ',
    Struct = ' ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = ' ',
    Locked = '',
    Rename = '',
    Question = '',
    Ignored = '',
    UnStage = '󰄷',
    Staged = '󰄸',
    Conflict = '',
  },
  Other = {
    Progress = '󰲽',
    Quickfixlogo = '🧛',
    Module = '󰕳',
    Gear = '',
    Arrow = '󰣉',
    Workspace = ''
  },
}

return M
