local M = {
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  git = {
    added = ' ',
    modified = ' ',
    removed = ' ',
    topdelete = '󰚃',
    changedelete = '󰮈',
    untracked = '',
    branch = '',
    renamed = '',
    ignored = '',
    unstaged = '󰄷',
    staged = '󰄸',
    conflict = '',
  },
  kinds = {
    Array = '󰅨',
    Boolean = ' ',
    Class = ' ',
    Color = ' ',
    Constant = ' ',
    Constructor = ' ',
    Copilot = ' ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = '󰈮 ',
    Folder = ' ',
    Function = ' ',
    Interface = ' ',
    Key = ' ',
    Keyword = ' ',
    Method = ' ',
    Module = ' ',
    Namespace = ' ',
    Null = ' ',
    Number = ' ',
    Object = ' ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    String = ' ',
    Struct = ' ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = ' ',
    Locked = '',
    Rename = '',
    Question = '',
    Ignored = '',
    UnStage = '󰄷',
    Staged = '󰄸',
    Conflict = '',
  },
  Other = {
    Progress = '󰲽',
    Quickfixlogo = '🧛',
    Module = '󰕳',
    Gear = '',
    Arrow = '󰣉',
    Workspace = '',
    Session = '',
    Group = '󰾂',
    FullArrow = '',
  },
  Menu = {
    buffer = '󰯰',
    nvim_lsp = '󰰣',
    path = '󰰚',
    nvim_lua = '󰢱',
    cmdline = '',
    Copilot = '',
  },
  dap = {
    Stopped = { '󰁕 ', 'DiagnosticWarn', 'DapStoppedLine' },
    Breakpoint = ' ',
    BreakpointCondition = ' ',
    BreakpointRejected = { ' ', 'DiagnosticError' },
    LogPoint = '.>',
  },
  biscuits = {
    Prefix = '',
    Html = '󰌝',
    Javascript = '󰌞',
  },
  todo = {
    Fix = '',
    Todo = '',
    Hack = '󰈸',
    Warn = '',
    Perf = '󱛢',
    Note = '󰠮',
    Test = '󰇉',
  }
}

return M
