return {
  "Mr-LLLLL/treesitter-outer",
  dependencies = "nvim-treesitter/nvim-treesitter",
  ft = {
    "c",
    "cpp",
    "go",
    "javascript",
    "lua",
    "python",
    "rust",
    "scss",
    "css",
    "tsx",
    "typescript",
  },
  opts = {
    filetypes = {
      "c",
      "cpp",
      "go",
      "javascript",
      "lua",
      "python",
      "rust",
      "scss",
      "css",
      "tsx",
      "typescript",
    },
    mode = { "n", "v" },
    prev_outer_key = "<A-n>",
    next_outer_key = nil,
  },
}
